/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AbmMaterial;
import javax.swing.JTextField;

/**
 *
 * @author Luca
 */
public class GestionarMaterial extends javax.swing.JDialog {

    /**
     * Creates new form GestionarMaterial
     */
    public GestionarMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JTextField getCampoCodigoMaterial() {
        return campoCodigoMaterial;
    }

    public void setCampoCodigoMaterial(JTextField campoCodigoMaterial) {
        this.campoCodigoMaterial = campoCodigoMaterial;
    }

    public JTextField getCampoDescripcionMaterial() {
        return campoDescripcionMaterial;
    }

    public void setCampoDescripcionMaterial(JTextField campoDescripcionMaterial) {
        this.campoDescripcionMaterial = campoDescripcionMaterial;
    }

    public JTextField getCampoPrecioMaterial() {
        return campoPrecioMaterial;
    }

    public void setCampoPrecioMaterial(JTextField campoPrecioMaterial) {
        this.campoPrecioMaterial = campoPrecioMaterial;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoCodigoMaterial = new javax.swing.JTextField();
        campoDescripcionMaterial = new javax.swing.JTextField();
        campoPrecioMaterial = new javax.swing.JTextField();
        botonAceptarMaterial = new javax.swing.JButton();
        botonCancelarMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Alta Material");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Descripcion:");

        jLabel4.setText("Precio:");

        campoCodigoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoMaterialActionPerformed(evt);
            }
        });

        campoDescripcionMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescripcionMaterialActionPerformed(evt);
            }
        });

        campoPrecioMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecioMaterialActionPerformed(evt);
            }
        });

        botonAceptarMaterial.setText("Aceptar");
        botonAceptarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarMaterialActionPerformed(evt);
            }
        });

        botonCancelarMaterial.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAceptarMaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelarMaterial))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoCodigoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDescripcionMaterial)
                    .addComponent(campoPrecioMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCodigoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoDescripcionMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrecioMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarMaterial)
                    .addComponent(botonCancelarMaterial))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoMaterialActionPerformed

    private void campoDescripcionMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescripcionMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescripcionMaterialActionPerformed

    private void campoPrecioMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecioMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecioMaterialActionPerformed

    private void botonAceptarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarMaterialActionPerformed
        int codigo = Integer.parseInt(getCampoCodigoMaterial().getText());
        String descripcion = getCampoDescripcionMaterial().getText();
        int precio = Integer.parseInt(getCampoPrecioMaterial().getText());
        
        AbmMaterial.agregarMaterial(codigo, descripcion, precio);
        setVisible(false);
    }//GEN-LAST:event_botonAceptarMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionarMaterial dialog = new GestionarMaterial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarMaterial;
    private javax.swing.JButton botonCancelarMaterial;
    private javax.swing.JTextField campoCodigoMaterial;
    private javax.swing.JTextField campoDescripcionMaterial;
    private javax.swing.JTextField campoPrecioMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
